In [1]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[11  7 24 12  6 12]
 [ 6 19 29 23 17  6]
 [17  3 27  8 11 20]
 [25 20 19 15 25 21]
 [16 12 15 17 27 22]]


In [3]:
bool_arr = a > 20
print(bool_arr)

[[False False  True False False False]
 [False False  True  True False False]
 [False False  True False False False]
 [ True False False False  True  True]
 [False False False False  True  True]]


In [5]:
ans = a[bool_arr]
print(ans)

[24 29 23 27 25 25 21 27 22]


In [7]:
b = a
print(a)

[[11  7 24 12  6 12]
 [ 6 19 29 23 17  6]
 [17  3 27  8 11 20]
 [25 20 19 15 25 21]
 [16 12 15 17 27 22]]


In [9]:
b[bool_arr] = 100
print(b)

[[ 11   7 100  12   6  12]
 [  6  19 100 100  17   6]
 [ 17   3 100   8  11  20]
 [100  20  19  15 100 100]
 [ 16  12  15  17 100 100]]


In [10]:
c = np.random.randint(1,10, (2,2))
c

array([[8, 8],
       [9, 6]])

In [11]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [14]:
#print(c[c_bool])

In [16]:
print(b)

[[ 11   7 100  12   6  12]
 [  6  19 100 100  17   6]
 [ 17   3 100   8  11  20]
 [100  20  19  15 100 100]
 [ 16  12  15  17 100 100]]


In [17]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False  True False False False]


In [18]:
b[bool_arr, 3] = 99
print(b)

[[ 11   7 100  12   6  12]
 [  6  19 100  99  17   6]
 [ 17   3 100   8  11  20]
 [100  20  19  15 100 100]
 [ 16  12  15  17 100 100]]


In [20]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x)
print(y)

[[8 2 6]
 [9 9 6]
 [1 6 1]]
[[9 2 2]
 [8 1 9]
 [4 5 9]]


In [21]:
ans = x-y
print(ans)

[[-1  0  4]
 [ 1  8 -3]
 [-3  1 -8]]


In [23]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,))
print(x)
print(y)

[[3 9 2]
 [4 2 3]
 [7 7 4]]
[4 4 2]


In [25]:
ans = x-y
print(ans)

[[-1  5  0]
 [ 0 -2  1]
 [ 3  3  2]]


In [29]:
x = np.random.randint(1, 10, (3,2))
y = np.random.randint(1, 10, (2,3))
print(x)
print(y)

[[3 9]
 [1 1]
 [4 1]]
[[2 1 7]
 [6 9 8]]


In [31]:
y = np.transpose(y)
print(y)
ans = x-y
print(ans)

[[2 6]
 [1 9]
 [7 8]]
[[ 1  3]
 [ 0 -8]
 [-3 -7]]


In [1]:
import numpy as np
x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)
print(y.shape)

(1, 2)


In [1]:
py -m pip install opencv-python

SyntaxError: invalid syntax (807128326.py, line 1)

In [2]:
python -m pip install opencv-python

SyntaxError: invalid syntax (1667370696.py, line 1)

In [3]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [4]:
pip install opencv

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement opencv (from versions: none)
ERROR: No matching distribution found for opencv


In [5]:
pip install opencv-python


     -------------------------------------- 35.6/35.6 MB 774.1 kB/s eta 0:00:00


In [1]:
import cv2

In [1]:
import cv2

img = cv2.imread('Downloads/download.jpg')

cv2.imshow('download', img)



cv2.waitKey(0) 
cv2.destroyAllWindows()


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:967: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [4]:
pip uninstall opencv-python-headless

Note: you may need to restart the kernel to use updated packages.


In [2]:

sudo pip install pypng

SyntaxError: invalid syntax (4003404632.py, line 1)

In [4]:
import cv2

img = cv2.imread(r'Downloads/download.jpg')

cv2.imshow('download', img)



cv2.waitKey(0) 
cv2.destroyAllWindows()


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:967: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [6]:
import cv2
img= cv2.imread('Downloads/download.jpg')
newImg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [ ]:
pip uninstall opencv-python

In [ ]:
import cv2

In [2]:
import numpy as np
a = np.array((1,3,4,57))
print(a)

[ 1  3  4 57]


In [13]:
#c=np.arange(5)
c = np.random.randint(1,10,(3,4))
s = np.random.randint(1,5,(3,4))
d=np.add(c,s)
print(c)
print(s)
print(d)

[[3 5 8 1]
 [3 8 1 7]
 [1 2 6 2]]
[[3 2 3 2]
 [2 1 3 4]
 [1 2 3 2]]
[[ 6  7 11  3]
 [ 5  9  4 11]
 [ 2  4  9  4]]


In [20]:
f = np.arange(8).reshape(2,4)
f

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
import pandas as pd

df = pd.DataFrame({
    "col1": [-5, -2, 1, 4],
    "col2": [2, 3, -1, 4]
})

def highlight_number(row):
    return[
        "background-color: red; color: white"
        if cell <= 0
        else "background-color: green; color: white"
        for cell in row
    ]

df.style.apply(highlight_number)