In [3]:
import numpy as np

In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
import time
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized version:" + str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(10000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

2499671.6591826114
vectorized version:14.178037643432617ms
2499671.65918227
For loop:5651.964426040649ms


In [13]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [14]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [15]:
percentage = 100*A/(cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [16]:
import numpy as np
b=np.random.randn(5)
print(b)

[ 0.1854426  -0.59662457  0.85042107 -0.32996593 -1.26316501]


In [17]:
print(b.shape)

(5,)


In [18]:
print(b.T)

[ 0.1854426  -0.59662457  0.85042107 -0.32996593 -1.26316501]


In [19]:
print(np.dot(b,b.T))

2.8180291992054722


In [20]:
b=np.random.randn(5,3)
print(b)

[[-0.16553943  0.54756135 -1.63656493]
 [-0.19810509  1.53375801  0.75580813]
 [ 0.44354249 -0.28192664  0.54125571]
 [ 1.05354001 -0.56466183  0.72856078]
 [-1.7869188  -1.33414332  0.17241733]]


In [21]:
print(b.T)

[[-0.16553943 -0.19810509  0.44354249  1.05354001 -1.7869188 ]
 [ 0.54756135  1.53375801 -0.28192664 -0.56466183 -1.33414332]
 [-1.63656493  0.75580813  0.54125571  0.72856078  0.17241733]]


In [22]:
print(np.dot(b,b.T))

[[ 3.00557152 -0.36430827 -1.11359601 -1.67592643 -0.71689195]
 [-0.36430827  2.9629052  -0.1111898  -0.52411408 -1.56194087]
 [-1.11359601 -0.1111898   0.56917031  1.02082065 -0.32312202]
 [-1.67592643 -0.52411408  1.02082065  1.95959035 -1.00363415]
 [-0.71689195 -1.56194087 -0.32312202 -1.00363415  5.00274492]]


In [23]:
import numpy as np
c=np.random.randn(8,1)
print(c.reshape(2,2,2))

[[[-0.51597166 -0.6619442 ]
  [ 1.32339013 -0.43139754]]

 [[-0.46209406 -0.3885253 ]
  [ 1.00133797 -1.71060658]]]


In [24]:
import numpy as np
a=np.random.randn(4,3) # a.shape = (3, 3)a.shape=(3,3)

b=np.random.randn(1,3) # b.shape = (2, 1)b.shape=(2,1)

c=a*b
print(c.reshape(4,3))

[[-0.03596923  0.00370235  0.38008199]
 [ 0.4937325   0.06447588 -0.12893519]
 [-0.06898664 -0.03252297 -0.27952614]
 [ 0.16184261 -0.10058836 -0.11148195]]


In [25]:
import numpy as np
a=np.array([[2,1],[1,3]])
print(a*a)

[[4 1]
 [1 9]]


In [26]:
import numpy as np
x = np.random.rand(4, 5)

y = np.sum(x, axis=1)
print(y)

[3.38118167 2.64791874 1.76297787 3.01772841]


In [ ]:
pip install markdown

In [ ]:
 pip install --upgrade pip 